### ISSUE TITLE
Dispatching with graphql-java

### ISSUE THREAD

**Issue by glasser** [nidomiro/KDataLoader#10]
Has anybody used this successfully with graphql-java? The docs allude to how this is useful for GraphQL but don't give a concrete example of how to use it.

The trick with graphql-java is figuring out where to insert the `dispatch` calls. Ideally you want them to be roughly "when the queue is empty", like in Node.

The Java DataLoader has integration with graphql-java itself, but that integration is very constrictive — it only works if you invoke DataLoader directly from the synchronous part of the field fetcher (ie, you can't use two DataLoaders in series in one fetcher). https://github.com/graphql-java/graphql-java/issues/1198 has the details.

**Comment by nidomiro** [comment]
Hi @glasser,
you can find examples for how to use it here: https://nidomiro.github.io/KDataLoader/KDataLoader/0.3.0/basic-usage.html

Currently there is no integration for graphql-java.
If you want you can write one and contribute the code or a integration-library it would be very helpful for others in your position right now.

If you have any more questions feel free to ask :)
