### ISSUE TITLE
Some real world examples?

### ISSUE THREAD

**Issue by RIP21** [nidomiro/KDataLoader#11]
Hi, currently it's super unclear how to use it with [graphql-kotlin](https://github.com/ExpediaGroup/graphql-kotlin) let say, or with `graphql-java`.

Like, I'm unsure when and where I can call dispatch in case of `graphql-koltin` to execute data loaders and to get results returned back to my resolvers.

Also, on the right side of your docs website, there are unused sections in the nav :) Remove them as it looks super unpolished.
Overall, the lack of examples and real-world scenarios make it unusable at least in the case of using `graphql-kotlin`. Maybe it's clearer how to do that with `graphql-java`, but I'm not super familiar as I'm using `graphql-kotlin`.

Thanks. I really hope for more examples. As for now I'm not even sure how to import Dataloader instance :D
As even in the example below

```kotlin
fun main(): Unit = runBlocking {
    val batchLoader: BatchLoader<Int, Int> = { keys -> keys.map { ExecutionResult.Success(it) } }
    val dataLoader = dataLoader(batchLoader)

    val value1 = dataLoader.loadAsync(1)
    val value2 = dataLoader.loadAsync(2)
    dataLoader.dispatch()

    println("1 -> ${value1.await()}")
    println("2 -> ${value2.await()}")
}
```

I can see where `batchLoader` is came from, but how is `dataLoader` has been created? :D Any class name, or, imports, dunno :D

**Comment by nidomiro** [comment]
Hi @RIP21,

Yea I know the website isn't the prettiest - I'll update it maybe some time in the future ;)

Regarding your Question on where to use it: I would use it in the Resolver("Controller") or the Service level in Spring terminology. The right position depends on your use-case.
If you use hibernate or something similar you probably already have a similar functionality build-in: the L1/L2 cache (See https://www.journaldev.com/2969/hibernate-caching-first-level-cache for more info).

The whole goal of this library is to save performance by avoiding duplicate calls eg. to an Database/Service/...

If you want some working examples, you can look at a test-case or the unstriped examples:
* https://github.com/nidomiro/KDataLoader/blob/master/src/commonTest/kotlin/nidomiro/kdataloader/dsl/DataLoaderDSLTest.kt#L98
* https://github.com/nidomiro/KDataLoader/tree/master/docs/modules/ROOT/examples

Is your question answered?

**Comment by RIP21** [comment]
All good. Only question where to call dispatch :) Because graphql-java dataloader calls it somewhere automatically somewhere at least in case of spring usage :) Unsure where should I put this one :)
