### ISSUE TITLE
JCenter closing down

### ISSUE THREAD

**Issue by jeggy** [nidomiro/KDataLoader#12]
As JCenter is closing down, it would be great if you could move this project to MavenCentral or some other stable place.

KGraphQL(https://github.com/aPureBase/KGraphQL/issues/134) has moved over to MavenCentral and users are reporting issues regarding KDataLoader not beeing resolved.

**Comment by nidomiro** [comment]
I'll work on migration to MavenCentral

**Comment by nidomiro** [comment]
https://issues.sonatype.org/browse/OSSRH-67336

**Comment by nidomiro** [comment]
Online on Maven Central: https://repo1.maven.org/maven2/de/nidomiro/
