### ISSUE TITLE
Simplify usage by changing BatchLoader

### ISSUE THREAD

**Issue by jeggy** [nidomiro/KDataLoader#5]
```kotlin
suspend (ids: List<K>) -> List<ExecutionResult<R>>
```
to
```kotlin
suspend (ids: Set<K>) -> Map<K, ExecutionResult<R>>
```
Changing the `BatchLoader` like that would simplify the whole usage and removes the need to be careful about returning a **sorted** list.

Sample usage after this change:
```kotlin
@Test
fun `create a basic DataLoader`() = runBlockingWithTimeout {
    val dataLoader = dataLoader({ keys: Set<Int> ->
        // We return a map, so it doesn't matter what order we execute this
        keys.reversed().map {
            it to ExecutionResult.Success(it.toString())
        }.toMap()
    })


    val deferred1 = dataLoader.loadAsync(1)
    val deferred2 = dataLoader.loadAsync(1)
    val deferred3 = dataLoader.loadAsync(3)
    dataLoader.dispatch()
    assertThat(deferred1.await()).isEqualTo("1")
    assertThat(deferred2.await()).isEqualTo("1")
    assertThat(deferred3.await()).isEqualTo("3")
}
```

**Comment by nidomiro** [comment]
Could you give me an example please, where the map is easier to deal with?

**Comment by jeggy** [comment]
Was just an idea after I first looked at this library. But now after I have worked with this for a while, I actually don't think something like this would bring any real benefit 😋

Maybe the idea with using `Set` instead of `List` would be something, as there should never be any duplicates within the keys provided to the loader method. But other than that I think you could just close this issue
